models/MachineDetail.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\FileHelper;
use yii\imagine\Image;

/**
 * This is the model class for table "machine_detail".
 *
 * @property int $id
 * @property int $machine_id
 * @property string $name
 * @property string|null $description
 * @property string|null $image
 * @property string|null $position
 * @property int $status
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class MachineDetail extends \yii\db\ActiveRecord
{
    public $mediaFile;
    const MEDIA_DIR = 'uploads/images/';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'machine_detail';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['machine_id', 'name'], 'required'],
            [['machine_id', 'status', 'created_at', 'updated_at'], 'integer'],
            [['description'], 'string'],
            [['name', 'image', 'position'], 'string', 'max' => 255],
            ['mediaFile', 'required', 'on' => 'create']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Mã chi tiết máy',
            'machine_id' => 'Mã máy',
            'name' => 'Tên chi tiết máy',
            'description' => 'Mô tả',
            'image' => 'Ảnh',
            'position' => 'Vị trí',
            'status' => 'Trạng thái',
            'mediaFile' => 'Ảnh',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => time(),
            ],
        ];
    }
    
    public function upload() {
        if ($this->validate('mediaFile')) {
            $dir = self::MEDIA_DIR.Yii::$app->user->identity->id . '_mcdetail';
            if(!file_exists($dir)) {
                FileHelper::createDirectory($dir);
            }
            $path = $dir.'/'.time() . '_' . Yii::$app->security->generateRandomString(5) . 
                    '_'. md5($this->mediaFile->baseName) . '.' . $this->mediaFile->extension;
            $this->mediaFile->saveAs($path);
            $this->image = '/'.$path;
            $this->createImageThumb();
            return true;
        } else {
            return false;
        }
    }
    
    public function createImageThumb($source = false) {
        if($source == false) {
            $source = $this->image;
        }
        $thumbName = $this->getThumbName($source);
        $coverThumbName = $this->getThumbName($source, '/cover_');
        
        $origin = Yii::getAlias('@webroot'.$source);
        $thumb = Yii::getAlias('@webroot'.$thumbName);
        $cover = Yii::getAlias('@webroot'.$coverThumbName);
        
        if(file_exists($origin)) {
            Image::thumbnail($origin, 300, 200)
                ->save($thumb, ['quality' => 70]);
            
            Image::thumbnail($origin, 171, 180)
                ->save($cover, ['quality' => 70]);
            return true;
        }
        return false;
    }
    
    public function getThumbName($source = false, $prefix='/thumb_') {
        if($source == false) {
            $source = $this->image;
        }
        $baseName = basename($source);
        $dirName = dirname($source);
        $thumbName = $prefix . $baseName;
        return $dirName.$thumbName;
    }
}

controllers/MachineController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Machine;
use app\models\searchs\MachineSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MachineController implements the CRUD actions for Machine model.
 */
class MachineController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Machine models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MachineSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Machine model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Machine model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Machine();
        $model->scenario = 'create';
        
        if($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->upload()) {
                if($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Machine model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->mediaFile) {
                $model->upload();
            }
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Machine model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Machine model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Machine the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Machine::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/MachineDetailController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MachineDetail;
use app\models\searchs\MachineDetailSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MachineDetailController implements the CRUD actions for MachineDetail model.
 */
class MachineDetailController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MachineDetail models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MachineDetailSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MachineDetail model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new MachineDetail model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MachineDetail();
        $model->scenario = 'create';
        $machine = Yii::$app->request->get('machine_id', '');
        
        $machine = intval($machine);
        if($machine > 0) {
            $model->machine_id = $machine;
        }
        
        if($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->upload()) {
                if($model->save()) {
                    return $this->redirect(['/machine/view', 'id' => $model->machine_id]);
                }
            }
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * Updates an existing MachineDetail model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->mediaFile) {
                $model->upload();
            }
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing MachineDetail model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MachineDetail model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MachineDetail the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MachineDetail::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/machine-detail/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use app\models\Machine;

/* @var $this yii\web\View */
/* @var $model app\models\MachineDetail */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="machine-detail-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'machine_id')->dropDownList(Machine::getList(), ['prompt'=>'----Chọn máy----']) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?php 
        $pluginOptions = ['maxFileSize' => 30000];
        echo $form->field($model, 'mediaFile')->widget(FileInput::classname(), [
            'options' => ['multiple' => false, 'accept' => 'image/*'],
            'pluginOptions' => $pluginOptions
        ]); 
    ?>

    <?= $form->field($model, 'position')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/machine-detail/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\searchs\MachineDetailSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="machine-detail-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'machine_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'position') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/machine-detail/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MachineDetail */

$this->title = Yii::t('app', 'Thêm chi tiết máy');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Máy'), 'url' => ['/machine/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="machine-detail-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/machine-detail/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\detail\DetailView;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $searchModel app\models\searchs\MachineDetailSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Machine Details');
$this->params['breadcrumbs'][] = $this->title;

$this->registerJs("$(function() {
    $('.model-push').click(function(e) {
        e.preventDefault();
        $('#modal').modal('show').find('.modal-content')
        .html($(this).attr('data'));
    });
});", yii\web\View::POS_READY);

?>
<div class="machine-detail-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create Machine Detail'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    
    <?php 
    Modal::begin([
        'header' => '<h4 class="modal-title">Chi tiết máy</h4>',
        'id' => 'modal',
        'size' => Modal::SIZE_LARGE
    ]);
    
    Modal::end();
    ?>
    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'machine_id',
            'name',
            'description:ntext',
            'image',
            [
                'attribute' => 'Thử', 
                'format' => 'raw',
                'value' => function($model) {
                    $data = DetailView::widget([
                        'model' => $model,
                        'condensed' => true,
                        'hover' => true,
                        'mode' => DetailView::MODE_VIEW,
                        'panel' => [
                            'heading' => '<i class="glyphicon glyphicon-book"></i> Chi tiết # ' . $model->id,
                            'type' => DetailView::TYPE_INFO,
                        ],
                        'attributes' => [
                            [
                                'group' => true,
                                'label' => 'THÔNG TIN',
                                'rowOptions' => ['class'=>'info'],
                                'groupOptions'=>['class'=>'text-center']
                            ],
                            'name',
                            [
                                'attribute' => 'description',
                                'format' => 'raw',
                                'value' => '<span class="text-justify"><em>' . $model->description . '</em></span>',
                                'type' => DetailView::INPUT_TEXTAREA, 
                                'options' => ['rows'=>4]
                            ],
                            [
                                'attribute' => 'image',
                                'format' => 'raw',
                                'value' => '<img src="'.$model->image.'" alt="'.$model->name.'">'
                            ],
                        ]
                    ]);
                    return  Html::a(Yii::t('app', 'Chi tiết'), 
                            ['#'], 
                            ['class' => 'btn btn-success model-push', 'id' => 'popupModal-'.$model->id, 'data' => $data]);
                }
            ],
            
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/machine-detail/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\MachineDetail */

$this->title = Yii::t('app', 'Update Machine Detail: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Machine Details'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="machine-detail-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/machine-detail/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\MachineDetail */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Machine Details'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="machine-detail-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'machine_id',
            'name',
            'description:ntext',
            'image',
            'position',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>