models/Machine.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\FileHelper;
use yii\imagine\Image;
/**
 * This is the model class for table "machine".
 *
 * @property int $id
 * @property string $name
 * @property string|null $description
 * @property string|null $image
 * @property int|null $type
 * @property string|null $version
 * @property int $status
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class Machine extends \yii\db\ActiveRecord
{
    public $mediaFile;
    const MEDIA_DIR = 'uploads/images/';
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'machine';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['description'], 'string'],
            [['type', 'status', 'created_at', 'updated_at'], 'integer'],
            [['name', 'image', 'version'], 'string', 'max' => 255],
            ['mediaFile', 'required', 'on' => 'create']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Mã máy',
            'name' => 'Tên máy',
            'description' => 'Mô tả',
            'image' => 'Ảnh',
            'type' => 'Loại máy',
            'version' => 'Phiên bản',
            'status' => 'Trạng thái',
            'mediaFile' => 'Ảnh',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => time(),
            ],
        ];
    }
    
    public function upload() {
        if ($this->validate('mediaFile')) {
            $dir = self::MEDIA_DIR.Yii::$app->user->identity->id;
            if(!file_exists($dir)) {
                FileHelper::createDirectory($dir);
            }
            $path = $dir.'/'.time() . '_' . Yii::$app->security->generateRandomString(5) . 
                    '_'. md5($this->mediaFile->baseName) . '.' . $this->mediaFile->extension;
            $this->mediaFile->saveAs($path);
            $this->image = '/'.$path;
            $this->createImageThumb();
            return true;
        } else {
            return false;
        }
    }
    
    public function createImageThumb($source = false) {
        if($source == false) {
            $source = $this->image;
        }
        $thumbName = $this->getThumbName($source);
        $coverThumbName = $this->getThumbName($source, '/cover_');
        
        $origin = Yii::getAlias('@webroot'.$source);
        $thumb = Yii::getAlias('@webroot'.$thumbName);
        $cover = Yii::getAlias('@webroot'.$coverThumbName);
        
        if(file_exists($origin)) {
            Image::thumbnail($origin, 300, 200)
                ->save($thumb, ['quality' => 70]);
            
            Image::thumbnail($origin, 171, 180)
                ->save($cover, ['quality' => 70]);
            return true;
        }
        return false;
    }
    
    public function getThumbName($source = false, $prefix='/thumb_') {
        if($source == false) {
            $source = $this->image;
        }
        $baseName = basename($source);
        $dirName = dirname($source);
        $thumbName = $prefix . $baseName;
        return $dirName.$thumbName;
    }
    
    public static function getList() {
        $models = self::find()->all();
        $data = [];
        if($models) {
            foreach($models as $model) {
                $data[$model->id] = $model->name;
            }
        }
        return $data;
    }
    
    public function getMachineDetails() {
        return $this->hasMany(MachineDetail::className(), ['machine_id' => 'id']);
    }
}

models/MachineType.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "machine_type".
 *
 * @property int $id
 * @property string $name
 * @property string|null $description
 * @property int $status
 * @property int|null $created_at
 * @property int|null $updated_at
 */
class MachineType extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'machine_type';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['description'], 'string'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => time(),
            ],
        ];
    }
    
    public static function getLabels() {
        $models = self::find()->all();
        $res = [];
        if($models) {
            foreach($models as $model) {
                $res[$model->id] = $model->name;
            }
        }
        return $res;
    }
}

controllers/MachineController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Machine;
use app\models\searchs\MachineSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MachineController implements the CRUD actions for Machine model.
 */
class MachineController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Machine models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MachineSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Machine model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Machine model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Machine();
        $model->scenario = 'create';
        
        if($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->upload()) {
                if($model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Machine model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->mediaFile) {
                $model->upload();
            }
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Machine model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Machine model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Machine the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Machine::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/MachineDetailController.php
<?php

namespace app\controllers;

use Yii;
use app\models\MachineDetail;
use app\models\searchs\MachineDetailSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MachineDetailController implements the CRUD actions for MachineDetail model.
 */
class MachineDetailController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MachineDetail models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MachineDetailSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MachineDetail model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new MachineDetail model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MachineDetail();
        $model->scenario = 'create';
        $machine = Yii::$app->request->get('machine_id', '');
        
        $machine = intval($machine);
        if($machine > 0) {
            $model->machine_id = $machine;
        }
        
        if($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->upload()) {
                if($model->save()) {
                    return $this->redirect(['/machine/view', 'id' => $model->machine_id]);
                }
            }
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * Updates an existing MachineDetail model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $model->mediaFile = UploadedFile::getInstance($model, 'mediaFile');
            if($model->mediaFile) {
                $model->upload();
            }
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing MachineDetail model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MachineDetail model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MachineDetail the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MachineDetail::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

views/machine/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\MachineType;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\models\Machine */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="machine-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?php 
        $pluginOptions = ['maxFileSize' => 30000];
        echo $form->field($model, 'mediaFile')->widget(FileInput::classname(), [
            'options' => ['multiple' => false, 'accept' => 'image/*'],
            'pluginOptions' => $pluginOptions
        ]); 
    ?>

    <?= $form->field($model, 'type')->dropDownList(MachineType::getLabels(), ['prompt'=>'----Chọn loại----']) ?>

    <?= $form->field($model, 'version')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/machine/_machine.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>
<div class="post" style="margin-top: 5px;">
    <div class="col-xs-6 col-md-3" id="<?php echo 'machine-item-'.$model->id;?>">
        <div class="thumbnail">
            <a href="/machine/view?id=<?=$model->id;?>" target="_blank" title="<?=$model->name;?>">
                <img src="<?=$model->getThumbName();?>" alt="<?=$model->name;?>">
            </a>
            <div class="caption">
                <p class="hls-caption" style="display: block; line-height: 18px; max-height: 36px; overflow: hidden;  height: 36px;"><?=$model->name;?></p>
                <p>
                    <a style="margin-bottom: 5px;" href="/machine/view?id=<?=$model->id;?>" 
                       style="margin-left: 5px;" title="Xem" class="btn btn-success" 
                       role="button"><span class="glyphicon glyphicon-eye-open"></span></a>
                       
                    <a style="margin-bottom: 5px;" href="/machine/update?id=<?=$model->id;?>" 
                       style="margin-left: 5px;" title="Sửa" class="btn btn-info" 
                       role="button"><span class="glyphicon glyphicon-edit"></span></a>
                    
                    <a style="margin-bottom: 5px; margin-left: 5px;"
                       class="btn btn-danger media-item-delete" 
                       title="Xóa" aria-label="Xóa" 
                       href="/machine/delete?id=<?=$model->id;?>"
                       data-media-id="<?=$model->id;?>"
                       data-confirm="Are you sure you want to delete this item?" 
                       data-method="post">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

views/machine/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\searchs\MachineSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="machine-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1,
            'class' => 'form-inline'
        ],
    ]); ?>

    
    <?= $form->field($model, 'name')->textInput(['placeholder' => 'Nhập tên máy'])->label(false) ?>

    <?= $form->field($model, 'type')->dropDownList(\app\models\MachineType::getLabels(), ['prompt'=>'----Tất cả loại máy----']) ?>

    <div class="form-group" style="margin-bottom: 10px;">
        <?= Html::submitButton(Yii::t('app', 'Tìm kiếm'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Làm lại'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/machine/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Machine */

$this->title = Yii::t('app', 'Thêm máy');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Danh sách máy'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="machine-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/machine/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\widgets\ListView;
/* @var $this yii\web\View */
/* @var $searchModel app\models\searchs\MachineSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Danh sách máy');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="machine-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    <p>
        <?= Html::a(Yii::t('app', 'Thêm máy'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    
    <?php 
    echo ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_machine',
        'layout' => '<div class="row">
                        <div class="col-md-12">
                            {pager}{summary}
                        </div>
                    </div>
                    <div class="row">{items}</div>',
    ]);
    ?>
    
    <?php Pjax::end(); ?>

</div>

views/machine/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Machine */

$this->title = Yii::t('app', 'Cập nhật máy: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Danh sách máy'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Cập nhật');
?>
<div class="machine-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/machine/view.php
<?php

use yii\helpers\Html;
//use yii\widgets\DetailView;
use yii\web\View;

use kartik\detail\DetailView;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $model app\models\Machine */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Dánh sách máy'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
$this->registerJsFile(
    '@web/js/shieldui-all.min.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
$this->registerCssFile("@web/css/all.min.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
]);
$this->registerCssFile("@web/css/machine-detail.css", [
    'depends' => [\yii\bootstrap\BootstrapAsset::className()],
]);


$this->registerJs(
    '$(".tabs_div").shieldTabs();',
    View::POS_READY
);

$this->registerJs("$(function() {
    $('.model-push').click(function(e) {
        e.preventDefault();
        $('#modal').modal('show').find('.modal-content')
        .html($(this).attr('data'));
    });
});", View::POS_READY);

?>

<p>
    <?= Html::a(Yii::t('app', 'Thêm chi tiết máy'), ['/machine-detail/create', 'machine_id' => $model->id], ['class' => 'btn btn-success']) ?>
    <?= Html::a(Yii::t('app', 'Sửa'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    <?= Html::a(Yii::t('app', 'Xóa'), ['delete', 'id' => $model->id], [
        'class' => 'btn btn-danger',
        'data' => [
            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
            'method' => 'post',
        ],
    ]) ?>
</p>
<?php 
    Modal::begin([
        'header' => '<h4 class="modal-title">Chi tiết máy</h4>',
        'id' => 'modal',
        'size' => Modal::SIZE_LARGE
    ]);
    
    Modal::end();
?>
<div class="machine-view">
    <div class="row" style="margin-right: 0px !important; margin-left: 0px !important">
        <div class="col-md-12">
            <div class="row" id="gradient">
                <div class="col-md-6">
                    <img src="<?= $model->image;?>" class="img-responsive">
                </div>
                <div class="col-md-6" id="overview">
                    <div class="row">
                        <div class="col-xs-6 col-md-6">
                            <ul class="pb-product-details-ul">
                                <li><h3><strong><?=$model->name;?></strong></h3></li>
                                <li><span class="fa fa-calendar"><?=$model->version;?></span></li>
                            </ul>
                        </div>
                        <div class="col-xs-3 col-md-3 text-center" id="hits">
                            <span class="fa fa-bar-chart">&nbsp;24%</span>
                            <p>22,010,155 HITS</p>
                        </div>
                        <div class="col-xs-3 col-md-3 text-center" id="fan">
                            <a href="#"><span class="fa fa-heart">&nbsp;1904</span></a>
                            <p>BECOME A FAN</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-3 col-md-3 pb-product-details-fa">
                            <span class="fa fa-mobile fa-lg"></span>
                            <h3><strong>5.5"</strong></h3>
                            <p>1440x2560 pixels</p>
                        </div>
                        <div class="col-xs-3 col-md-3 pb-product-details-fa">
                            <span class="fa fa-camera fa-lg"></span>
                            <h3><strong>12 MP</strong></h3>
                            <p>2160p</p>
                        </div>
                        <div class="col-xs-3 col-md-3 pb-product-details-fa">
                            <span class="fa fa-microchip fa-lg"></span>
                            <h3><strong>4GB RAM</strong></h3>
                            <p>Exynos 8890</p>
                        </div>
                        <div class="col-xs-3 col-md-3 pb-product-details-fa">
                            <span class="fa fa-battery-4 fa-lg"></span>
                            <h3><strong>3600mAH</strong></h3>
                            <p>Li-ion</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="tabs_div">
                    <ul>
                        <li>Mô tả</li>
                        <li>Chi tiết</li>
                    </ul>
                    <div>
                        <table class="table">
                            <tbody>
                                <tr class="row">
                                    <td class="success col-md-3">Tính năng và hoạt động: </td>
                                    <td><?=$model->description?></td>
                                </tr>
                                <tr class="row">
                                    <td class="success col-md-3">Đời máy: </td>
                                    <td><?=$model->version?></td>
                                </tr>
                                <tr class="row" style="border-bottom: 1px solid #ddd;">
                                    <td class="success col-md-3">Loại máy: </td>
                                    <td><?= \app\models\MachineType::getLabels()[$model->type]?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div>
                        <table class="table">
                            <tbody>
                                <?php 
                                $i = 0;
                                $size = sizeof($model->machineDetails);
                                ?>
                                <?php foreach($model->machineDetails as $detail): ?>
                                    <?php $i ++;?>
                                    <tr class="row" style="<?php echo ($i == $size)?'border-bottom: 1px solid #ddd;':''?>" >
                                        <td class="success col-md-3"><?=$detail->name?>: </td>
                                        <td><?=$detail->description?></td>
                                        <?php 
                                        $data = DetailView::widget([
                                            'model' => $detail,
                                            'condensed' => true,
                                            'hover' => true,
                                            'mode' => DetailView::MODE_VIEW,
                                            'panel' => [
                                                'heading' => '<i class="glyphicon glyphicon-book"></i> Chi tiết # ' . $detail->id,
                                                'type' => DetailView::TYPE_INFO,
                                            ],
                                            'attributes' => [
                                                [
                                                    'group' => true,
                                                    'label' => 'THÔNG TIN',
                                                    'rowOptions' => ['class'=>'info'],
                                                    'groupOptions'=>['class'=>'text-center']
                                                ],
                                                'name',
                                                [
                                                    'attribute' => 'description',
                                                    'format' => 'raw',
                                                    'value' => '<span class="text-justify"><em>' . $detail->description . '</em></span>',
                                                    'type' => DetailView::INPUT_TEXTAREA, 
                                                    'options' => ['rows' => 4]
                                                ],
                                                [
                                                    'attribute' => 'image',
                                                    'format' => 'raw',
                                                    'value' => '<img src="'.$detail->image.'" alt="'.$detail->name.'">'
                                                ],
                                            ]
                                        ]);
                                        ?>
                                        <td col-md-1>
                                            <?php 
                                            echo Html::a(Yii::t('app', '<span class="glyphicon glyphicon-eye-open"></span>'), 
                                            ['#'], 
                                            ['class' => 'btn btn-success model-push', 'id' => 'popupModal-'.$detail->id, 'data' => $data]);
                                            ?>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>